groupadd ca;
useradd -g ca ca;
useradd -g ca ocsp;
useradd signer -m -s /bin/bash;
echo "signer:signer" | chpasswd; 
cp -r etc /;
cp -r home /;
cp -r usr /;
chmod +x  /usr/local/bin/*;
cd /home/ca/CA;
chmod +x *sh;
./init.sh;
chown ca:ca /home/ca/CA;
chmod g+r /home/ca/CA;
touch /var/log/ocsp.log;
chown ca:ca /var/log/ocsp.log;
chmod g+rw /var/log/ocsp.log;
/sbin/start ocsp;
