Vagrant.configure("2") do |config|

 config.vm.provider "virtualbox" do |v|
   v.customize ["modifyvm", :id, "--memory", "1536"]
  end

  config.vm.define "sc" do |sc|
  sc.vm.box = "ubuntu/xenial64"
  sc.vm.hostname="servidorcentral"
  sc.vm.network "private_network", ip: "10.0.10.10"
  sc.vm.provision :shell, path: "servidorCentral.sh"
  end

  config.vm.define "ss1" do |ss1|
  ss1.vm.box = "ubuntu/xenial64"
  ss1.vm.hostname="tenoli1"
  ss1.vm.network "private_network", ip: "10.0.10.11"
  ss1.vm.provision :shell, path: "servidorSeguridad.sh"
  end

  config.vm.define "ss2" do |ss2|
  ss2.vm.box = "ubuntu/xenial64"
  ss2.vm.hostname="tenoli2"
  ss2.vm.network "private_network", ip: "10.0.10.12"
  ss2.vm.provision :shell, path: "servidorSeguridad.sh"
  end

  config.vm.define "ca" do |ca|
  ca.vm.box = "ubuntu/xenial64"
  ca.vm.hostname="certificadora"
  ca.vm.network "private_network", ip: "10.0.10.13"
  ca.vm.provision "shell", inline: <<-SHELL
     apt-get update 
     apt-get install -y nginx-light;
     cd /vagrant/openssl-ca; chmod +x instalar.sh;
     ./instalar.sh;
   SHELL
  end
end
