groupadd ca;
useradd -g ca ocsp;
useradd -g ca ca;
useradd signer -m -s /bin/bash;
echo "signer:signer" | chpasswd; 
cp ocsp.service /etc/systemd/system/;
cp tsa.service /etc/systemd/system/;
cp -r etc /;
cp -r home /;
cp -r usr /;
chmod g+r /home/ca/CA;
chmod +x  /usr/local/bin/*;
cd /home/ca/CA;
chmod +x *sh;
./init.sh;
touch /var/log/ocsp.log;
chown ca:ca /var/log/ocsp.log;
chown -R ca:ca /home/ca/CA;
chmod g+rw /var/log/ocsp.log;
systemctl enable ocsp.service;
systemctl start ocsp.service;
systemctl enable tsa.service;
systemctl start tsa.service;
systemctl restart nginx.service;
