Vagrant.configure("2") do |config|

  config.vm.define "sc" do |sc|
  sc.vm.box = "ubuntu/bionic64"
  sc.vm.provider "virtualbox" do |sc|
      sc.customize ["modifyvm", :id, "--memory", "1536"] 
  end 
  sc.vm.hostname="servidorcentral"
  sc.vm.network "private_network", ip: "10.0.10.10"
  sc.vm.provision :shell, path: "servidorCentral.sh"
  end

 config.vm.define "ss1" do |ss1|
  ss1.vm.box =  "ubuntu/bionic64"
  ss1.vm.hostname="tenoli-ss1"
  ss1.vm.provider "virtualbox" do |ss1|
      ss1.customize ["modifyvm", :id, "--memory", "2048"] 
  end
  ss1.vm.network "private_network", ip: "10.0.10.11"
  ss1.vm.provision :shell, path: "servidorSeguridad.sh"
  end

#  config.vm.define "ss2" do |ss2|
#  ss2.vm.box = "generic/rhel7"
#  ss2.vm.hostname="tenoli-ss2"
#  ss2.vm.provider "virtualbox" do |ss2|
#      ss2.customize ["modifyvm", :id, "--memory", "2048"]
#  end
#  ss2.vm.network "private_network", ip: "10.0.10.12"
#  end

  config.vm.define "ca" do |ca|
  ca.vm.box = "ubuntu/bionic64"
  ca.vm.hostname="certificadora"
  ca.vm.provider "virtualbox" do |ca|
      ca.customize ["modifyvm", :id, "--memory", "1024"]
  end
  ca.vm.network "private_network", ip: "10.0.10.13"
  ca.vm.provision :shell, path: "openssl-ca/instalar.sh"
  end
end
