groupadd ca;
useradd ca;
useradd ocsp;
useradd signer -m -s /bin/bash;
echo "signer:signer" | chpasswd; 
usermod -aG ca ocsp;
cp -r etc /;
cp -r home /;
cp -r usr /;
chown ca:ca /home/ca/CA;
chmod g+r /home/ca/CA;
chmod +x  /usr/local/bin/*;
cd /home/ca/CA;
chmod +x *sh;
./init.sh;
touch /var/log/ocsp.log;
chown ca:ca /var/log/ocsp.log;
chmod g+rw /var/log/ocsp.log;
/sbin/start ocsp;
/sbin/start ocsp;
